import tree from "./model/pattern-tree";

require("fs")
  .createWriteStream(__dirname + "/pattern-tree.snapshot.ts")
  .write(
    "// THIS FILE IS AUTOGENERATED. DO NOT EDIT\nexport default " +
      JSON.stringify(tree()) +
      "\n"
  );
